//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CAOTHUONG\\CAOTHUONG;Initial Catalog=QUANLYQUANHEKHACHHANG;Integrated " +
            "Security=True")]
        public string QUANLYQUANHEKHACHHANGConnectionString {
            get {
                return ((string)(this["QUANLYQUANHEKHACHHANGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CAOTHUONG\\CAOTHUONG;Initial Catalog=QLQUANHEKHACHHANG;Integrated Secu" +
            "rity=True")]
        public string QLQUANHEKHACHHANGConnectionString {
            get {
                return ((string)(this["QLQUANHEKHACHHANGConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool nhanvien {
            get {
                return ((bool)(this["nhanvien"]));
            }
            set {
                this["nhanvien"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\BUS\\QUANLYQUANHEKHAC" +
            "HHANG.mdf;Integrated Security=True;Connect Timeout=30")]
        public string QUANLYQUANHEKHACHHANGConnectionString1 {
            get {
                return ((string)(this["QUANLYQUANHEKHACHHANGConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\QUANLYQUANHEKHACHHAN" +
            "G.mdf;Integrated Security=True;Connect Timeout=30")]
        public string QUANLYQUANHEKHACHHANGConnectionString2 {
            get {
                return ((string)(this["QUANLYQUANHEKHACHHANGConnectionString2"]));
            }
        }
    }
}
