CREATE DATABASE QUANLYQUANHEKHACHHANG
GO
USE QUANLYQUANHEKHACHHANG
GO

CREATE TABLE SANPHAM
(
	MaSP			varchar(10) NOT NULL	PRIMARY KEY,
	TenSP			nvarchar(50) NOT NULL,
	NuocSX			nvarchar(50) NOT NULL,
	GiaSP			float NULL,
	DonVi			NVARCHAR(10) NULL,
	NgaySX			DATETIME,
)

CREATE TABLE NHOM_ND
(
	MaNhomND					varchar(10) NOT NULL	PRIMARY KEY,
	TenNhomND					nvarchar(30) NOT NULL,
 )
 
 
 CREATE TABLE NHOM_KH
 (
	MaNhomKH			varchar(10) NOT NULL	PRIMARY KEY,
	TenNhomKH			nvarchar(35) NOT NULL,
 )
 
 
 CREATE TABLE NHANVIEN
 (
	MaNV				varchar(10) NOT NULL	PRIMARY KEY,
	TenNV				nvarchar(50) NOT NULL,
	NgaySinh			DATETIME,
	DiaChi				nvarchar(50) NOT NULL,
	SDT					int NOT NULL,
	CMND				int NOT NULL,
	Anh					nvarchar(50) NULL,
	Luong				float NULL,
	Email				varchar(50) NOT NULL,
)


CREATE TABLE KHACHHANG
(
	MaKH				varchar(10) NOT NULL	PRIMARY KEY,
	MaNhomKH			varchar(10) NULL		FOREIGN KEY REFERENCES NHOM_KH(MaNhomKH) ON UPDATE CASCADE,
	TenKH				nvarchar(50) NOT NULL,
	DiaChiKH				nvarchar(50) NOT NULL,
	SoDienThoai				int NOT NULL,
	CMND					int NOT NULL,
	Email					varchar(50) NOT NULL,
	NgaySinh				DATETIME,
 )


CREATE TABLE LICHHEN
(
	Ma_LH				varchar(10) NOT NULL	PRIMARY KEY,
	MaNV				varchar(10) NOT NULL	FOREIGN KEY REFERENCES NHANVIEN(MaNV) ON UPDATE CASCADE,
	MaKH				varchar(10) NOT NULL	FOREIGN KEY REFERENCES KHACHHANG(MaKH) ON UPDATE CASCADE,
	NgayHen				DATETIME,
	NgayGap				DATETIME,
	NoiDung_LH			nvarchar(1000) NOT NULL,
 )
 
 
 CREATE TABLE HOTRO
 (
	MaHT				varchar(10) NOT NULL PRIMARY KEY,
	MaKH				varchar(10) NOT NULL	FOREIGN KEY REFERENCES KHACHHANG(MaKH) ON UPDATE CASCADE,
	MaNV				varchar(10) NOT NULL	FOREIGN KEY REFERENCES NHANVIEN(MaNV) ON UPDATE CASCADE,
	NoiDung				nvarchar(1000) NOT NULL,
	TG_HT				DATETIME,
 )
 
 
 CREATE TABLE HOPDONG
 (
	MaHD				varchar(10) NOT NULL PRIMARY KEY,
	MaKH				varchar(10) NOT NULL	FOREIGN KEY REFERENCES KHACHHANG(MaKH) ON UPDATE CASCADE,
	MaNV				varchar(10) NOT NULL	FOREIGN KEY REFERENCES NHANVIEN(MaNV) ON UPDATE CASCADE,
	TenHD				nvarchar(50) NOT NULL,
	NgayKy				DATETIME,
	NgayBD				DATETIME,
	NgayKT				DATETIME,
	TinhTrang				nvarchar(60) NOT NULL,
	TriGia					float NOT NULL,
 )
 
 CREATE TABLE GUI_MAIL
 (
	Ma_GM				varchar(10) NOT NULL	PRIMARY KEY,
	MaNV				varchar(10) NOT NULL	FOREIGN KEY REFERENCES NHANVIEN(MaNV) ON UPDATE CASCADE,
	MaKH				varchar(10) NOT NULL	FOREIGN KEY REFERENCES KHACHHANG(MaKH) ON UPDATE CASCADE,
	NoiDungGM			nvarchar(200) NOT NULL,
	TG_Gui				DATETIME,
 )
 
 CREATE TABLE GIAODICH
 (
	Ma_GD				varchar(10) NOT NULL PRIMARY KEY,
	MaHD				varchar(10) NOT NULL FOREIGN KEY REFERENCES HOPDONG(MaHD) ON UPDATE CASCADE,
	TenGD				nvarchar(50) NOT NULL,
	NgayGD				DATETIME,
	DiaDiemGD			nvarchar(50) NOT NULL,
)

CREATE TABLE CTHD
(
	MaSP					varchar(10) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP) ON UPDATE CASCADE,
	MaHD					varchar(10) NOT NULL FOREIGN KEY REFERENCES HOPDONG(MaHD) ON UPDATE CASCADE,
	SoLuong					int NOT NULL,
	ThanhTien				float NOT NULL
	
	PRIMARY KEY(MaSP,MaHD)
)


CREATE TABLE THUCHI
(
	MaKhoan					varchar(10) NOT NULL	PRIMARY KEY,
	Ma_GD					varchar(10) NULL		FOREIGN KEY REFERENCES GIAODICH(Ma_GD) ON UPDATE CASCADE,
	TenKhoan				nvarchar(50) NOT NULL,
	NgayTH					DATETIME,
	NguoiTH					varchar(10) NOT NULL,
	NguoiNhan				varchar(10) NOT NULL,
	Tien					float NOT NULL
 )
 
 CREATE TABLE NGUOIDUNG
 (
	Ten_ND 				varchar(50) PRIMARY KEY,
	MaNhomND 			varchar(10) FOREIGN KEY REFERENCES NHOM_ND(MaNhomND) ON UPDATE CASCADE,
	MaNV				varchar(10) NOT NULL	FOREIGN KEY REFERENCES NHANVIEN(MaNV) ON UPDATE CASCADE,
	MatKhau				varchar(10)
 )